# Generated by Django 3.2.16 on 2023-06-11 04:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('feeds', '0015_alter_about_about_avatar'),
    ]

    operations = [
        migrations.RenameField(
            model_name='personalinformation',
            old_name='mycv',
            new_name='stack_overflow',
        ),
    ]
